apiVersion: v1
kind: Namespace
metadata:
  name: app-prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-repo
  namespace: app-prometheus
spec:
  interval: 5m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-prometheus
  namespace: app-prometheus
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
      version: 26.1.0
  interval: 10m0s