apiVersion: v1
kind: Namespace
metadata:
  name: app-grafana
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-repo
  namespace: app-grafana
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-grafana
  namespace: app-grafana
spec:
  chart:
    spec:
      chart: app-grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
      version: 8.8.2
  interval: 10m0s